version: '3.2'

services:
  elasticsearch:
    ports:
      - "9200:9200"
    image: elasticsearch:8.2.0
    environment:
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
